-- MySQL Script generated by MySQL Workbench
-- Mon Nov 29 17:21:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`guns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gun_name` VARCHAR(100) NOT NULL,
  `ammo_name` VARCHAR(45) NOT NULL,
  `nation` VARCHAR(20) NOT NULL,
  `ammo_type` VARCHAR(45) NOT NULL,
  `barrel_lenght` INT UNSIGNED NOT NULL,
  `caliber` INT UNSIGNED NOT NULL,
  `muzzle_velocity` INT UNSIGNED NOT NULL,
  `pen_100` INT UNSIGNED ZEROFILL NULL,
  `pen_300` INT UNSIGNED ZEROFILL NULL,
  `pen_500` INT UNSIGNED ZEROFILL NULL,
  `pen_1000` INT UNSIGNED ZEROFILL NULL,
  `pen_1500` INT UNSIGNED ZEROFILL NULL,
  `pen_2000` INT UNSIGNED ZEROFILL NULL,
  `pen_3000` INT UNSIGNED ZEROFILL NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehicles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vehicle_name` VARCHAR(100) NOT NULL,
  `nation` VARCHAR(45) NOT NULL,
  `front_armor_thickness` INT NOT NULL,
  `side_armor_thickness` INT NOT NULL,
  `front_armor_angle` INT NOT NULL,
  `side_armor_angle` INT NOT NULL,
  `gun_id` INT NOT NULL,
  PRIMARY KEY (`id`, `gun_id`),
  INDEX `gun_idx` (`gun_id` ASC) INVISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_gun_id`
    FOREIGN KEY (`gun_id`)
    REFERENCES `mydb`.`guns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saved_tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saved_tests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vehicle_id` INT NOT NULL,
  `test_date` TIMESTAMP NOT NULL,
  `target_vehicle_id` INT NOT NULL,
  `shot_angle` INT NOT NULL,
  `result` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `vehicle_idx` (`vehicle_id` ASC) INVISIBLE,
  INDEX `target_vehicle_idx` (`target_vehicle_id` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saved_tests_has_target_vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saved_tests_has_target_vehicles` (
  `saved_tests_target_vehicle_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  INDEX `vehicle_idx` (`vehicle_id` ASC) INVISIBLE,
  INDEX `saved_tests_target_vehicle_idx` (`saved_tests_target_vehicle_id` ASC) INVISIBLE,
  CONSTRAINT `fk_saved_tests_target_vehicle_id`
    FOREIGN KEY (`saved_tests_target_vehicle_id`)
    REFERENCES `mydb`.`saved_tests` (`target_vehicle_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_id`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `mydb`.`vehicles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saved_tests_has_vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saved_tests_has_vehicles` (
  `saved_tests_vehicle_id` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  INDEX `vehicle_idx` (`vehicle_id` ASC) INVISIBLE,
  INDEX `saved_tests_vehicle_idx` (`saved_tests_vehicle_id` ASC) VISIBLE,
  CONSTRAINT `fk_saved_tests_vehicle_id`
    FOREIGN KEY (`saved_tests_vehicle_id`)
    REFERENCES `mydb`.`saved_tests` (`vehicle_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_id`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `mydb`.`vehicles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
